package com.example.golfdistancetracker.util

object GolfTips {
    val all = listOf(
        "La presión del agarre (3/10): En una escala del 1 al 10, sujetá el palo con una fuerza de 3 o 4. Demasiada tensión en las manos bloquea las muñecas y resta velocidad.",
        "Ajuste de ancho de pies: Para wedges, pies al ancho de hombros; para hierros medios, un poco más ancho; para el Driver, talones por fuera de los hombros.",
        "Codo derecho como 'bandeja': En la cima del backswing, el codo derecho debe apuntar hacia el suelo formando un ángulo de 90°, como si sostuvieras una bandeja.",
        "La toalla bajo la axila: Practicá con una toalla bajo la axila del brazo delantero para evitar desacoplar los brazos del torso durante el swing.",
        "Pie delantero abierto: Girá la punta del pie delantero unos 15° a 20° hacia el objetivo para facilitar la rotación de caderas en la bajada.",
        "Iniciar la bajada desde abajo: El downswing nace desde el apoyo de los pies y la rotación de caderas, no desde las manos.",
        "La pausa invisible: Intentá sentir una micro-pausa en la cima del backswing para sincronizar el cambio de ritmo sin apurar las manos.",
        "Mantené la inclinación de columna: No intentes 'levantar' la pelota incorporando el pecho. Mantené la inclinación de la espalda del setup.",
        "Extensión de brazos post-impacto: Tras pegarle a la bola, proyectá ambos brazos extendidos hacia el objetivo antes de que doblen.",
        "Ver los nudillos en el grip: Deberías ver al menos 2 nudillos de tu mano delantera. Si ves menos, tu grip es 'débil' y favorece el slice.",
        "Mantené el radio del swing: El brazo delantero debe mantenerse extendido durante todo el backswing para crear el arco más amplio posible.",
        "Pecho al objetivo en la terminación: Termina con el pecho y la cadera mirando al objetivo y el peso 100% sobre la pierna delantera.",
        "Regla 70/30 en el chip: Apoyá el 70% de tu peso sobre la pierna delantera desde el setup y mantenelo ahí durante todo el movimiento.",
        "Cero muñecas en el chip corto: Imaginá que tus hombros y brazos forman un triángulo rígido y movelo como un péndulo.",
        "Usa la suela (Bounce), no el Filo: Para los pitches, dejá que la parte ancha inferior deslice sobre el césped para no clavar el palo.",
        "Regla del 80% en Wedges: Nunca le pegues a un wedge al 100%. A máxima potencia perdés control de distancia y generás exceso de spin.",
        "Chip con el Híbrido: En el rough pegado al green, usá un híbrido con el movimiento de un putt para un rodamiento suave.",
        "Control por longitud de swing: Regulá distancias de pitches según la altura de las manos: cintura (9:00), pecho (10:00) u hombro (11:00).",
        "Manos por delante en el impacto: Para un chip limpio, las manos deben llegar ligeramente por delante de la cara del palo al tocar la bola.",
        "Cuidado con el Lob Wedge (60°): Es el palo más riesgoso. Si no hay obstáculos altos, preferí un Pitching o Sand Wedge.",
        "Alineación de ojos sobre la bola: En el putt, los ojos deben estar exactamente en la vertical sobre la pelota para evitar distorsiones ópticas.",
        "Marcá una línea en la pelota: Usá la línea impresa de tu pelota para apuntar exactamente hacia el punto de salida que leíste.",
        "La velocidad manda sobre la caída: Un putt fuerte borra parte de la caída; uno suave la duplica. Priorizá siempre la distancia.",
        "Punta de la cara en bajada: En putts rápidos cuesta abajo, impactá la bola ligeramente con la punta del putter para suavizar el rodamiento.",
        "Escuchá la pelota caer: En putts cortos, mantené la cabeza mirando el piso hasta escuchar la bola entrar. Mover la cabeza antes desvía el tiro.",
        "Leé el green desde el punto más bajo: Para ver mejor las caídas pronunciadas, agachate a mirar la línea desde el sector más bajo del terreno.",
        "El ritual de la moneda: Colocá el marcador siempre justo detrás de la bola. Es una pausa excelente para calmar las pulsaciones.",
        "Misma aceleración de ida y vuelta: El backswing y el follow-through en el putt deben mantener la misma amplitud y ritmo fluido.",
        "Abrí la cara del búnker ANTES del grip: Si rotás la cara del Sand Wedge después de tomar el palo, tus manos la cerrarán al bajar.",
        "Enterrá los pies en la arena: Gira los pies al entrar al búnker para ganar estabilidad y sentir la dureza de la arena.",
        "Pegale a la arena, no a la pelota: En búnker de green, impactá la arena 2-4 cm antes de la bola. El colchón de arena la elevará.",
        "Swing decidido en búnker: No frenes el palo por miedo. Dejá que la cabeza atraviese la arena con fluidez y aceleración.",
        "Pelota enterrada (Fried Egg): Si está hundida, cerrá la cara del palo y atacá con un swing más inclinado para 'cavar'.",
        "Búnker de Fairway: Usá un palo más del habitual, poné la pelota al centro y buscá un contacto limpio pelota-arena.",
        "La regla de los 10 pasos: Si hacés un tiro pésimo, tenés 10 pasos para enojarte. Al paso 11, olvidalo y enfócate en el siguiente.",
        "Aceptá el tiro malo: El golf es gestión de errores. Gana quien comete los errores menos graves, no solo tiros perfectos.",
        "Zona de decisión vs. Ejecución: Pensá la estrategia detrás de la bola. Al pararte al lado, apagá la mente analítica y ejecutá.",
        "Si estás incómodo, ABORTÁ: Si escuchás un ruido o no te hallás en la postura, salite de la pelota y empezá la rutina de cero.",
        "Enfocate en el objetivo, no en el obstáculo: No pienses 'no ir al agua'. El cerebro procesa la imagen. Pensá en el árbol del centro.",
        "Respiración diafragmática: Exhalá despacio justo antes de iniciar la rutina para liberar la tensión en hombros y cuello.",
        "Apuntá al centro del green: Olvidate de banderas peligrosas. Tirar al centro garantiza mejores scores y evita desastres.",
        "Usa el Tee Box a tu favor: Si el peligro está a la derecha, salí desde el margen derecho del tee apuntando a la izquierda.",
        "El 'Spot Alignment': Elegí una marca en el suelo a 1 metro delante de tu bola alineada con tu objetivo. Es mucho más fácil apuntar ahí.",
        "Sacar de costado desde el bosque: Si estás atrapado, no intentes el tiro milagroso. Jugá de costado al fairway y asegurá el Bogey.",
        "El Layup estratégico: En Par 5, dejá la bola a una distancia donde te quede un swing completo de tu wedge favorito.",
        "Conocé tu tiro por defecto: Si tu tiro natural es un fade (curva a la derecha), apunta al lado izquierdo. No luches contra tu vuelo natural.",
        "Evaluá el 'Lie' antes de decidir: El estado del césped dicta el tiro. Mirá si la pelota está flotando o hundida antes de elegir palo.",
        "Viento en contra, bajá el esfuerzo: No pegues más fuerte; subí 2 palos y hacé un swing fluido al 70% para reducir el spin.",
        "Viento a favor = menos frenado: Volará más, pero al caer al green rodará mucho más porque pierde backspin.",
        "Hombros paralelos a la pendiente: En tiros con inclinación, acomodá la línea de tus hombros al ángulo del terreno.",
        "Cuesta abajo sale a la derecha: Ajustá tu alineación; tiros en subida tienden a cerrarse (hook) y en bajada a abrirse (slice).",
        "Freno por frío o lluvia: El aire frío es denso y el agua frena el vuelo. Calculá 5-10 metros menos en días invernales.",
        "Terreno seco y duro: Ganás rodamiento pero el palo puede rebotar si pegás pesado. Buscá un contacto de 'barrido' más plano.",
        "Limpiá las estrías siempre: Si están llenas de tierra, la pelota sale sin control ni spin. Tené siempre una toalla a mano.",
        "Cambiá los grips una vez al año: Grips gastados te obligan a apretar con más fuerza, generando tensión innecesaria.",
        "Usá siempre el mismo modelo de pelota: Cambiar de marca entre hoyos altera las distancias y la sensación en el green.",
        "Gapping de 4° a 6° en Wedges: Asegurate de que la diferencia de loft entre tus wedges sea pareja para no dejar huecos de distancia.",
        "Marcá tu pelota: Usá un marcador indeleble con un patrón propio. Jugar la pelota equivocada cuesta 2 golpes de penalidad.",
        "Chequeá los clavos de tus zapatos: La tracción es la base para transferir la fuerza del suelo al palo sin resbalar.",
        "Rotación torácica antes de salir: Realizá giros de torso con un palo detrás de la nuca para activar la columna antes de tirar.",
        "No calientes con el Driver: Arrancá con wedges o hierros cortos haciendo swings suaves y subí de palo progresivamente.",
        "Fuerza desde las piernas: El poder del swing nace de la presión contra el suelo, no de la fuerza de los brazos.",
        "Hidratación constante: Bebé pequeños sorbos de agua cada 3 hoyos. La deshidratación afecta la concentración y coordinación.",
        "Estiramiento de flexores de cadera: Si pasás horas sentado, estirá las caderas antes de jugar para permitir un giro completo.",
        "El 'Toe-Putt' desde el rough bajo: En el borde del green, usá el putter pegándole con la punta para que no se enganche con el pasto.",
        "Sobre un árbol cercano: Poné la pelota adelante, usá el wedge de más loft y mantené el pecho abierto en el seguimiento.",
        "Arreglá los piques hacia adentro: Empujá el césped de los bordes hacia el centro del pique. Nunca apalanques las raíces hacia arriba.",
        "Pisar la arena antes de tirar: Observá tus huellas en el búnker. Si te hundís mucho, la arena está suave; si no, está compacta.",
        "Apoyar el palo suavemente en el rough: Si lo apoyás con pesadez, podés mover la bola accidentalmente y sumar una penalidad.",
        "Medir el viento con césped: Dejá caer unos hilos de césped a la altura de tus ojos para ver la dirección y velocidad real.",
        "La prueba de la moneda: Poné una moneda en el piso y practicá pasar la suela del wedge raspando justo por debajo sin clavar el palo.",
        "Evitar el 'Flyer' en el rough: Si la bola está suspendida, usá más loft; saldrá disparada con mucha velocidad y cero spin.",
        "Putter desde fuera del green: Si no hay pasto alto, usá el putter aunque estés fuera. Suele ser más seguro que un chip.",
        "Ajustá las marcas del tee box: Podés retrasar la pelota hasta 2 largos de palo hacia atrás para buscar un piso más plano.",
        "Mantené la rutina de tiempo exacta: Cronometrá tu rutina pre-golpe. Que dure siempre lo mismo te dará calma en el torneo."
    )
}
